// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txhcttlbotheqduwzjvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aGN0dGxib3RoZXFkdXd6anZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzA1NDEsImV4cCI6MjA2NjE0NjU0MX0.EFLOVyfaFc9LSXuX6BHNg0HKm_c2KY30E9PZYiWlTVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);